spring:
  application:
    name: Dynamic-DataSource

  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123


